### PR TITLE
fix(proto-gen): change uids for user in the container

### LINKED ISSUE #235: ubuntu docker + protoc gen issue
ref: https://github.com/rollchains/spawn/issues/226#issuecomment-2401197905

replicated on my Ubuntu server as well

Then somehow I broke my manjaro instance too i think. moving to a non docker approach

---

solved here - mostly permission issues - https://discord.com/channels/669268347736686612/1293574916704309269

### PR DESCRIPTION
**Pull request by reecepbcups**
closes #235

solved here - mostly permission issues - https://discord.com/channels/669268347736686612/1293574916704309269

### CODE REVIEW

**Comment by reecepbcups** [comment]
Tested on
- Majaro
- Ubuntu 22.04 LTS (Server)
- MacOS M3 
- Windows 10 laptop

All function as expected

**Comment by reecepbcups** [comment]
Discord user gets this (buf requires a cache to dump information, and for some reason his does not have perms)
image

**Comment by Reecepbcups** [comment]
solved! permission issues - https://discord.com/channels/669268347736686612/1293574916704309269

**Comment by reecepbcups** [comment]
Will do further testing when it is time for the v0.50.9 release

**Pull request merged**
