### PR TITLE
feat: ccv consumer democracy

### PR DESCRIPTION
**Pull request by reecepbcups**
## Summary
Get staking, gov, and distribution to work for ICS consumer chains. This way we can support Ethos

### CODE REVIEW

**Comment by reecepbcups** [comment]
At the moment, SetProperFeaturePairs() and changing consensus based on required dependencies is quite confusing. Since POA, POS, and ICS are the only current cosnensus this is fine, but will be some debt. Does not make sense to fix atm until we add another consensus like Saga, EVM, PoW, or Rollkit (I can't figure out the best design for it, another specific consensus should help).

**Comment by reecepbcups** [comment]
Turns out there is some special slashing stuff you have to do when using staking & consumer together. You init slashing with staking keeper usage for most. Then after setting up the consumerModule, set the slashing module again using ref to the ConsumerKeeper

**Comment by reecepbcups** [comment]
\`matrixicsbase fails IBC  atm for `failed to get funds from faucet: transaction failed with code 1: tx contains unsupported message types at height 134`

POA & Staking pass. I bet it is the Consumer ref thing

**Comment by reecepbcups** [comment]
I am hitting a context deadline issue now with the relayer. Unsure if this is relayer specific (as there are other issues around this) or due to `"could not retrieve public key for validator on consumer chain because the validator did not assign a new consumer key"` (which may be due to the relayer)

**Comment by reecepbcups** [comment]
I THINK THAT WAS IT

Tested with generation chains as well. Success (just not tested local-ic, in todo)

**Comment by Reecepbcups** [comment]
Will merge this after next tag for EthCC CosmosHub event

**Comment by reecepbcups** [comment]
getting into the next release per request

**Pull request merged**
